name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.7.2

      - name: Install dependencies
        run: npm install
        continue-on-error: true

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Cypress artifacts - Evidence videos
        if: always()  # Asegura que los artefactos se suban incluso si el paso anterior falla
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts-evidenceVideos
          path: |            
            cypress/screenshots
            cypress/videos

      - name: Generate HTML report
        run: |
          npm install multiple-cucumber-html-reporter --save-dev
          node cucumber-html-report.js --reportPath: ./reports/cucumber
          
      - name: Publish reports as artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-report
          path: ./reports/cucumber
